### PR TITLE
Hopefully the last CSS work

### PR DESCRIPTION
**Pull request by wickersl**

### CODE REVIEW

**Comment by donsisco** [comment]
screen shot 2016-11-09 at 8 05 46 pm

**Comment by wickersl** [comment]
Alright can someone else take a look at the CSS for profile.css as well as personal-profile.html to see what's up because I cannot for the life of me get the user icon to be constrained to a max-width and max-height. That's the only issue in my code. Googling did not help.

**Comment by donsisco** [comment]
Oh I can fix that one sec

**Review by donsisco — APPROVED** [review]
I like it :)

**Pull request merged**
